# Generated by Django 4.1.7 on 2023-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_start', models.CharField(max_length=4)),
                ('Session_end', models.CharField(max_length=4)),
            ],
        ),
    ]
