# Generated by Django 4.1.7 on 2023-03-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.course'),
        ),
    ]
